import mongoose from "mongoose";

const orderSchema=new mongoose.Schema({
    orderItems:[{
            product:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"Product",
                required:true,
            },
            name:{
                type:String,
                required:true,
            },
            price:{
                type:Number,
                required:true,
            },
            quantity:{
                type:Number,
                required:true,
                min:1,
            },
    },],
     user:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"User",
                required:true,
            },
            shippingAddress:{
                address:{
                    type:String,
                    required:true,
                },
                city:{
                    type:String,
                    required:true,
                },
                state:{
                    type:String,
                    required:true,
                },
                postalCode:{
                    type:String,
                    required:true,
                },
                country:{
                    type:String,
                    required:true,
                }
            },
            colorPreferences:[{
                type:String,
            }],
            colorNotes:{
                type:String,
                trim:true,
            },
            clothDeliveryMethod:{
                type:String,
                enum:["courier","in-person","not-needed"],
                default:"courier",
            },
            estimatedCompletionDays:{
                type:Number,
                min:1,
                default:null,
            },
            paymentStatus:{
                type:String,
                enum:["pending-after-delivery","received"],
                default:"pending-after-delivery",
            },
            totalPrice:{
                type:Number,
                required:true,
            },
            status:{
                type:String,
                enum:["pending","processing","shipped","delivered","cancelled"],
                default:"pending",
            },
},{timestamps:true});
const Order=mongoose.model("Order",orderSchema);
export default Order;
